"""initial

Revision ID: 7eaca3eb7039
Revises: 3efb8d6c6837
Create Date: 2024-02-10 20:15:48.838113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eaca3eb7039'
down_revision: Union[str, None] = '3efb8d6c6837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('report_path', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_info')
    # ### end Alembic commands ###
